name: Bug Report
description: Create a bug report
labels:
  - 'kind: bug'
body:
  - type: markdown
    attributes:
      value: >
        Thanks for reporting! 
        Please note that you should have a **short title** about describe what the bug is!
        If you have any further question, you can join my [Discord server](https://discord.gg/y2DxRWbYsF)!
  - type: textarea
    id: summary
    attributes:
      label: Description
      description: >
        Please provide an abstract description of the issue to the developers,
        and why you consider it to be a bug. Please include any specific links
        to the documentation, JSON specification, or code.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      description: >
        How do you trigger the bug? Please walk us through step by step. Be as
        specific as possible.
    validations:
      required: true
  - type: textarea
    id: results
    attributes:
      label: Expected vs. actual results
      description: >
        Please describe what you expected to happen after the steps above and
        what actually happened.
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Minimal code example
      description: >
        If possible, provide a small and self-contained example that triggers
        the bug. Please understand that we cannot analyze and debug large code
        bases. Please do not paste screenshots here.
      render: Shell
  - type: textarea
    id: output
    attributes:
      label: Error messages
      description: >
        Please provide any kind of error output (compilation errors, exception
        messages, stack traces, etc.) which can help to diagnose the error.
      render: Shell
  - type: input
    id: compiler
    attributes:
      label: Compiler and operating system
      description: >
        On which operating systems and compilers have you observed the issue?
        Include as many relevant details about the environment you experienced
        the bug in.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Library version
      description: >
        Which version of the library did you use? If it is a released version,
        please enter the version number (ex: v0.1.3.0). Otherwise, please enter
        the commit hash. If you got the library from another source as the
        GitHub repository (e.g., via a package manager), please also state
        this.
    validations:
      required: true
  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      description: >
        Please check these additional steps:
      options:
        - label: The bug also occurs if the latest version from the [`develop`](https://github.com/harshfeudal-projects/raiden-shogun/releases/latest) branch is used.
        - label: I have met all requirements about [your instructions](https://github.com/Harshfeudal-Projects/Raiden-Shogun/blob/main/README.md) on `REAMDE.md`.
